apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-config
  namespace: monitoring
data:
  agent.yaml: |
    server:
      http_listen_port: 12345
    prometheus:
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'cv-onepage'
          static_configs:
            - targets: ['localhost:80']
